[project]
name = "eval-suite-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "observer", email = "wozluohd@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["jinja2>=3.1.6", "pydantic>=2.11.4", "ray>=2.46.0"]

[project.scripts]
eval-suite-core = "eval_suite_core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
